### ISSUE TITLE
wrong path, make sure it's `/charge`

### ISSUE THREAD

**Issue by tri82wiyono** [rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#5]
wrong path, make sure it's `/charge`

**Comment by rizdaprasetya** [comment]
@tri82wiyono when asking a technical issue it will be very helpful to elaborate in detail and provide log/evidence of what are you trying to do, how, and what is the result.

I can only guess you hit wrong URL. Please follow the guide properly:
https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#usage
https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#troubleshooting
