### ISSUE TITLE
Server Side Midtrans mobile integration getting Error

### ISSUE THREAD

**Issue by imamabdulazis** [rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#7]
### wrong path, make sure it's `/charge`

`<?php
// Set your server key (Note: Server key for sandbox and production mode are different)
$server_key = 'SB-Mid-server-7xaCHZufo--NTBcJ0T3SXB9a';
// Set true for production, set false for sandbox
$is_production = false;

$api_url = $is_production ? 
  'https://app.midtrans.com/snap/v1/transactions' : 
  'https://app.sandbox.midtrans.com/snap/v1/transactions';

// Check if request doesn't contains `/charge` in the url/path, display 404
if( !strpos($_SERVER['REQUEST_URI'], '/charge') ) {
  http_response_code(404); 
  echo "wrong path, make sure it's `/charge`"; exit();
}
// Check if method is not HTTP POST, display 404
if( $_SERVER['REQUEST_METHOD'] !== 'POST'){
  http_response_code(404);
  echo "Page not found or wrong HTTP request method is used"; exit();
}

// get the HTTP POST body of the request
$request_body = file_get_contents('php://input');
// set response's content type as JSON
header('Content-Type: application/json');
// call charge API using request body passed by mobile SDK
$charge_result = chargeAPI($api_url, $server_key, $request_body);
// set the response http status code
http_response_code($charge_result['http_code']);
// then print out the response body
echo $charge_result['body'];

/**
 * call charge API using Curl
 * @param string  $api_url
 * @param string  $server_key
 * @param string  $request_body
 */
function chargeAPI($api_url, $server_key, $request_body){
  $ch = curl_init();
  $curl_options = array(
    CURLOPT_URL => $api_url,
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_POST => 1,
    CURLOPT_HEADER => 0,
    // Add header to the request, including Authorization generated from server key
    CURLOPT_HTTPHEADER => array(
      'Content-Type: application/json',
      'Accept: application/json',
      'Authorization: Basic ' . base64_encode($server_key . ':')
    ),
    CURLOPT_POSTFIELDS => $request_body
  );
  curl_setopt_array($ch, $curl_options);
  $result = array(
    'body' => curl_exec($ch),
    'http_code' => curl_getinfo($ch, CURLINFO_HTTP_CODE),
  );
  return $result;
}`

![Screen Shot 2020-11-13 at 1 12 23 AM](https://user-images.githubusercontent.com/39134128/98978999-5729d180-254d-11eb-9498-9583f96436e9.png)

Please help? what happened to my implementation?

**Comment by rizdaprasetya** [comment]
please try following the [troubleshooting section](https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#troubleshooting)

If still doesn't work, then your web server config is not standard/default. Try removing this line
https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-/blob/b02248fbcbc34a797e067a4b1a552efd849071d7/charge/index.php#L12-L16

**Comment by imamabdulazis** [comment]
Sory to be late answer your response sir.
Thanks for your response sir, my server now works normally.
