### ISSUE TITLE
Kenapa tidak bisa berfungsi untuk production?

### ISSUE THREAD

**Issue by ninepi09** [rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#8]
Tidak berfungsi jika diganti api key server dan cliebnt dgn yg production.makasi b4 atas tanggaoannya

**Comment by rizdaprasetya** [comment]
hi @ninepi09 
Ketika switch ke production pastikan hal hal berikut sudah diubah:
- ServerKey di backend sudah menggunakan Server Key akun production
- Jika ada variable `is_production` atau sejenisnya silahkan diubah jadi `true`
- Silahkan ikuti ini untuk di Mobile SDK implementationnya: https://mobile-docs.midtrans.com/#going-live-with-mobile-sdk

Sebaiknya silahkan email ke support[at]midtrans.com untuk mendapat tanggapan lebih cepat dan pengecekan lebih lanjut.

Thanks
