### ISSUE TITLE
404 The requested URL was not found on this server saat memanggil https://kalisaandroid.herokuapp.com/charge

### ISSUE THREAD

**Issue by cube76** [rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#9]
Selamat malam, saya mau bertanya saya mendapatkan 404 "The requested URL was not found on this server" saat memulai menjalankan UI midtrans di android. dan jika di aplikasinya dia bilang "failed to retreve response from server". saya sudah mengikuti sample yang disini padahal. Mohon bantuannya..

**Comment by rizdaprasetya** [comment]
Hi @cube76 di app heroku anda, file `./charge/index.php` anda host di root web directory, anda pindahkan tidak sesuai petunjuk. Pastikan filenya ada di subdirectory `/charge`. 

Goalnya adalah ketika ada HTTP POST request (dari mobile SDK) reach URL `https://kalisaandroid.herokuapp.com/charge` akan dihandle oleh file `./charge/index.php`.

Thanks. For better and faster response, please contact Midtrans support email.
